{
  "modified": "2025-07-31T19:16:15Z",
  "published": "2025-07-31T19:16:15Z",
  "schema_version": "1.5.0",
  "id": "",
  "aliases": [
    "MAL-2025-5126",
    "SNYK-PYTHON-READMECOLORAMA-10305013"
  ],
  "affected": [
    {
      "package": {
        "ecosystem": "PyPI",
        "name": "readmecolorama"
      }
    }
  ],
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://security.snyk.io/vuln/SNYK-PYTHON-READMECOLORAMA-10305013"
    },
    {
      "type": "ADVISORY",
      "url": "https://github.com/ossf/malicious-packages/blob/main/osv/malicious/pypi/readmecolorama/MAL-2025-5126.json"
    }
  ],
  "database_specific": {
    "malicious-packages-origins": [
      {
        "source": "reversing-labs",
        "sha256": "c0f43da6669cf9a48e88ad211fe0d2db630c4e94668c3a1feb12d5fef4db7d53",
        "import_time": "2025-08-01T10:41:35.405563504Z",
        "id": "RLUA-2025-03673",
        "modified_time": "2025-07-31T19:16:15Z"
      }
    ]
  }
}
