{
  "modified": "2025-08-28T07:11:54Z",
  "published": "2025-08-28T07:11:54Z",
  "schema_version": "1.5.0",
  "id": "",
  "affected": [
    {
      "package": {
        "ecosystem": "PyPI",
        "name": "sinontop-utils"
      }
    }
  ],
  "references": [
    {
      "type": "ARTICLE",
      "url": "https://www.fortinet.com/blog/threat-research/malicious-packages-across-open-source-registries"
    }
  ],
  "database_specific": {
    "malicious-packages-origins": [
      {
        "source": "reversing-labs",
        "sha256": "5ec866361fc18dcea178404d7af04fc3a5f87bc73d259ccc9e3329cd01e44fd9",
        "import_time": "2025-08-29T06:42:44.627555554Z",
        "id": "RLUA-2025-04257",
        "modified_time": "2025-08-28T07:11:54Z"
      }
    ]
  }
}
