{
  "modified": "2025-07-31T19:14:37Z",
  "published": "2025-07-31T19:14:37Z",
  "schema_version": "1.5.0",
  "id": "",
  "aliases": [
    "SNYK-PYTHON-COLORAMAPKGS-10305012",
    "MAL-2025-5103"
  ],
  "affected": [
    {
      "package": {
        "ecosystem": "PyPI",
        "name": "coloramapkgs"
      }
    }
  ],
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://github.com/ossf/malicious-packages/blob/main/osv/malicious/pypi/coloramapkgs/MAL-2025-5103.json"
    },
    {
      "type": "ADVISORY",
      "url": "https://security.snyk.io/vuln/SNYK-PYTHON-COLORAMAPKGS-10305012"
    }
  ],
  "database_specific": {
    "malicious-packages-origins": [
      {
        "source": "reversing-labs",
        "sha256": "d25a2fe2e2d149f4e4b6a8e845af645d3c010746046697df3cfab153efbd03cc",
        "import_time": "2025-08-01T10:41:34.939717972Z",
        "id": "RLUA-2025-03567",
        "modified_time": "2025-07-31T19:14:37Z"
      }
    ]
  }
}
