{
  "modified": "2025-09-26T09:14:39Z",
  "published": "2025-09-26T09:14:39Z",
  "schema_version": "1.5.0",
  "id": "",
  "aliases": [
    "MAL-2025-3006",
    "SNYK-PYTHON-TCLOUDPYTHONTEST-12201353"
  ],
  "affected": [
    {
      "package": {
        "ecosystem": "PyPI",
        "name": "tcloud-python-test"
      }
    }
  ],
  "references": [
    {
      "type": "WEB",
      "url": "https://x.com/ReversingLabs/status/1900198602242204003"
    },
    {
      "type": "ADVISORY",
      "url": "https://github.com/ossf/malicious-packages/blob/main/osv/malicious/pypi/tcloud-python-test/MAL-2025-3006.json"
    },
    {
      "type": "ADVISORY",
      "url": "https://security.snyk.io/vuln/SNYK-PYTHON-TCLOUDPYTHONTEST-12201353"
    }
  ],
  "database_specific": {
    "malicious-packages-origins": [
      {
        "source": "reversing-labs",
        "sha256": "5852c723e0b065d1baa10c7bf39fcc721dc7670afb0d2b0e6a2b3cdfb2ec75ca",
        "import_time": "2025-09-26T11:06:10.935474543Z",
        "id": "RLUA-2025-04811",
        "modified_time": "2025-09-26T09:14:39Z"
      }
    ]
  }
}
