{
  "modified": "2025-09-26T09:13:47Z",
  "published": "2025-09-26T09:13:47Z",
  "schema_version": "1.5.0",
  "id": "",
  "aliases": [
    "MAL-2025-41628"
  ],
  "affected": [
    {
      "package": {
        "ecosystem": "PyPI",
        "name": "celery-routr"
      }
    }
  ],
  "database_specific": {
    "malicious-packages-origins": [
      {
        "source": "reversing-labs",
        "sha256": "5a368915aeb03654b1d956ebc673d29f1022ea01b15b45c3219acfbe8c72b2b0",
        "import_time": "2025-09-26T11:06:09.994604597Z",
        "id": "RLUA-2025-04751",
        "modified_time": "2025-09-26T09:13:47Z"
      }
    ]
  }
}
