{
  "modified": "2025-07-31T19:14:38Z",
  "published": "2025-07-31T19:14:38Z",
  "schema_version": "1.5.0",
  "id": "",
  "aliases": [
    "MAL-2025-5105",
    "SNYK-PYTHON-COLORAMAPKGSW-10305009"
  ],
  "affected": [
    {
      "package": {
        "ecosystem": "PyPI",
        "name": "coloramapkgsw"
      }
    }
  ],
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://github.com/ossf/malicious-packages/blob/main/osv/malicious/pypi/coloramapkgsw/MAL-2025-5105.json"
    },
    {
      "type": "ADVISORY",
      "url": "https://security.snyk.io/vuln/SNYK-PYTHON-COLORAMAPKGSW-10305009"
    }
  ],
  "database_specific": {
    "malicious-packages-origins": [
      {
        "source": "reversing-labs",
        "sha256": "9c0012ed93dcccfd3ba55fc7e501d37c4f5b16c34204bfa5f784a7d009ad2d96",
        "import_time": "2025-08-01T10:41:35.073498013Z",
        "id": "RLUA-2025-03569",
        "modified_time": "2025-07-31T19:14:38Z"
      }
    ]
  }
}
