{
  "modified": "2025-09-26T09:14:23Z",
  "published": "2025-09-26T09:14:23Z",
  "schema_version": "1.5.0",
  "id": "",
  "aliases": [
    "MAL-2025-41715"
  ],
  "affected": [
    {
      "package": {
        "ecosystem": "PyPI",
        "name": "peloton-client123"
      }
    }
  ],
  "database_specific": {
    "malicious-packages-origins": [
      {
        "source": "reversing-labs",
        "sha256": "81d74cb5da7853f0b92c653b800931877636226b4694b80749b5d09be3355baa",
        "import_time": "2025-09-26T11:06:10.496784644Z",
        "id": "RLUA-2025-04799",
        "modified_time": "2025-09-26T09:14:23Z"
      }
    ]
  }
}
