{
  "modified": "2025-07-31T19:14:34Z",
  "published": "2025-07-31T19:14:34Z",
  "schema_version": "1.5.0",
  "id": "",
  "affected": [
    {
      "package": {
        "ecosystem": "PyPI",
        "name": "cloudx-auth",
        "purl": "pkg:pypi/cloudx-auth"
      },
      "versions": [
        "1.3.1"
      ]
    }
  ],
  "credits": [
    {
      "name": "ReversingLabs",
      "type": "FINDER",
      "contact": [
        "https://www.reversinglabs.com"
      ]
    }
  ],
  "database_specific": {
    "malicious-packages-origins": [
      {
        "source": "reversing-labs",
        "sha256": "a563601a7a339b185e43b0f1ba32c66f30717e58f3a328049ac5135394250637",
        "import_time": "2025-08-01T10:07:10.400403406Z",
        "id": "RLMA-2025-03564",
        "modified_time": "2025-07-31T19:14:34Z",
        "versions": [
          "1.3.1"
        ]
      }
    ]
  }
}
